var prompts = [
	'College I’m really passionate about this cause and I will give you this flier if I have to shove it down your throat',
	'College- vicious battle over the only left handed desk in the room',
	'College- my roommate’s boyfriend is staying over so can I please sleep on your floor',
	'College- it’s pouring and my final paper is in my backpack so I guess we’re stuck under this tiny awning together. do you think they’d deliver pizza here',
	'College- hey I have to photograph someone for class will you be my model',
	'College- hey I have to take someone’s blood pressure for class will you be my victim',
	'College- I know I keep coming to the cookie shop and for some reason it’s always your shift but don’t you dare judge me I need these for my sanity',
	'College- all our friends are drunk',
	'College- it’s 3 am and I’m still in the library studying for finals and I’m losing my grip on reality and I think I just saw a ghost',
	'College- we’re the only two people in this club. what is this club even for',
	'College- humans vs zombies',
	'College- we’re the only people who ever talk in discussions it’s awful',
	'College- GROUP PROJECT',
	'College- both of us turned up at the wrong room for this lecture but don’t know where its meant to be',
	'College- w have a competent lab partner?',
	'College- You’re the RA and you’re trying to bust me for having hermit crabs',
	'College- You’re baking cookies in the communal kitchen at 3am and I’m angry but also really hungry',
	'College- What are you doing at this table at the career fair',
	'College- Waiting for office hours',
	'College- I’ve been sitting in this seat all semester why did you decide to sit in it today',
	'College- Clearly we’re both really uncomfortable at this party',
	'College- You peed on my car. You were drunk. I was in the car. There will be hell to pay.',
	'College- We started racing up the three flights of stairs to class for some reason and we can’t stop',
	'College- You’re REALLY GOOD at using the right search terms for the academic databases and I’m on a deadline',
	'College- my friend dragged me to this party and I just saw my ex quick make out with me',
	'College- we’re always at the fitness center at the same time and end up competing on the treadmill',
	'College- Sorry my roommate puked on yoaiting outside for pizza to be delivered and both of ours are super late',
	'College- you keep parking in the space outside my student house you absolute asshole',
	'College- we live in halls opposite each other and I keep seeing you changing through your window',
	'College- you’re the only other person in the room when I break the printer and I’m panicking',
	'College- Neither of us bought the expensive textbook but there is only one copy in the library and it can’t leave the building',
	'College- This awesome professor only has one TA slot and we’re rivals',
	'College- I found your USB drive still in the computer',
	'College- I thought I was the only one who liked the waffle station in the cafeteria',
	'College- You reserving the good study room in the corner of the library with the windows',
	'College- We’re studying in the library and there are two people very obviously fucking in the stacks and we keep sharing embarrassed glances',
	'College- We’re both donating blood in the blood donation van in the quad to get out of the same class',
	'College- You decked me in the head while you were playing frisbee golf',
	'College- Can I borrow a dryer sheet? I ran out and the ones in the vending machine give me a rash',
	'College- Your school mailbox is right next to mine',
	'College- I saw you sneaking captain crunch and cutlery out of the dining hall',
	'College- Wait, I actually have a competent lab partner?',
	'College- You’re the RA and you’re trying to bust me for having hermit crabs',
	'College- You’re baking cookies in the communal kitchen at 3am and I’m angry but also really hungry',
	'College- What are you doing at this table at the career fair',
	'College- Waiting for office hours',
	'College- I’ve been sitting in this seat all semester why did you decide to sit in it today',
	'College- Clearly we’re both really uncomfortable at this party',
	'College- You peed on my car. You were drunk. I was in the car. There will be hell to pay.',
	'College- We started racing up the three flights of stairs to class for some reason and we can’t stop',
	'College- You’re REALLY GOOD at using the right search terms for the academic databases and I’m on a deadline',
	'College- my friend dragged me to this party and I just saw my ex quick make out with me',
	'College- we’re always at the fitness center at the same time and end up competing on the treadmill',
	'College- Sorry my roommate puked on your shoes',
	'College- Can I borrow a dryer sheet? I ran out and the ones in the vending machine give me a rash',
	'College- My roommate borrowed your contraband hotpot and managed to set it on fire',
	'College- You keep using my preferred shower stall in the floor bathrooms when I’m trying to get ready for class',
	'College- My computer crashed and you’re the student worker at the IT center',
	'College- we’re both on althetic teams that aren’t as cool as the football team and they give us shit',
	'College- You’re part of the guerrilla theater club on campus and crashed my class for a performance',
	'College- What do you mean we’re under a tornado warning?',
	'College- it’s 3am, in the dead of winter, some motherfucker pulled/set off the fire alarm and I am being very vocal about how I’m gonna make that fucker pay',
	'College- you’re the fucker who set off the fire alarm with your awful cooking',
	'College- I’m the fucker who set off the fire alarm with my awful cooking',
	'College- my shower isn’t working can I use yours',
	'College- RA mandated floor party',
	'College- I couldn’t help but notice you’re watching a show I like instead of studying in the computer lab',
	'College- dude your headphones are really loud like I can make out most of the lyrics and I’m sitting across the fucking room',
	'College- hey the semester’s almost over and I have way too much money on my cafeteria account, do you want anything??? this shit’s just gonna disappear into the college’s pocket otherwise',
	'College- THERE IS A BOUNCY CASTLE IN THE OVAL AND I AM VERY EXCITED',
	'College- I’ve ordered take out every night this week and you always seem to be my delivery person',
	'College- we’re both skipping class to study for a different class',
	'College- you live above me and I’m going to murder you if you don’t stop throwing parties Sunday night',
	'College- there’s only one study room left in the dorm basement and I don’t want to walk to the library, let’s fight for it',
	'College- I swear I’m wearing this Batman costume because of a dare',
	'College- The guy with the bibles on the quad has cornered me and is screaming about hell, please rescue me',
	'College- lecture room bingo for annoying things your prof says',
	'College- you’re obviously high or hungover so I’m going to rescue you and tell the teacher why your answer wasn’t as strange as it sounded, but you’ll owe me',
	'College- holy fuck you found me on the roof please don’t be an RA',
	'College- You’re standing right next to me while we’re both flyering and catching all of the people walking past before I can',
	'College- Alternatively, we’re standing right next to each other while flyering and hey, are you as miserable as I am right now?',
	'College- We can’t both listen to our music in the shower at the same time',
	'College- Both of us are super bored at this mandatory floor meeting',
	'College- We both work really late shifts on Friday Nights and you give me a ride home so I don’t have to walk alone in the dark',
	'College- You’re the only one who actually responded to the desperate message I sent to the whole class about needing the notes',
	'College- All the seats in this huge fucking lecture hall and you have to sit right next to me',
	'College- I’m sorry you caught me moving your clothes out of the dryer but in my defense I’ve been waiting for one to open up for about an hour now',
	'College- We were both running for the bus and it didn’t wait for us, so now we’re at this bus stop together alone',
	'College- Are you the one who keep leaving their dirty dishes in the common area kitchen',
	'College- You posted that you needed to borrow something on the floor’s facebook group and I just so happen to have what you need',
	'College- I want to buy your football ticket/textbook/etc so we have to meet up',
	'College- Every single table in the union is full, do you mind if I just sit here for a while?',
	'College- wait, you’re not the roommate i requested',
	'College- i wouldn’t have offered you a blunt if i’d known you were the RA',
	'College- we both got the same disgusting food at the diner and have no one else to complain to about it',
	'College- free STI testing at the health clinic… meeting when their hands touch as they reach for a free condom from the giant bowl on the counter',
	'College- we’re the only ones that signed up for this club, where the fuck is everyone else',
	'College- walking in on hot roommate masturbating oh my god',
	'College- got caught having an orgy in a classroom in the middle of the night',
	'College- we heard meningitis is going around and we’re both terrified and buying hand sanitizer in bulk',
	'College- the only ones in the dorm that go out for thirsty thursday',
	'College- the only competent ones in the group project',
	'College- are you asleep on that bench because of midterms, you’re homeless, or you’re dead?',
	'College- omg did you see me pet that squirrel???',
	'College- turns out that random hookup from the club sits right next to you in your favorite class',
	'College- skipping class to get high',
	'College- i really need to pass this midterm and rumor has it you have the best study guide',
	'College- met doing laundry at 2am',
	'College- accidentally knocked on the wrong dorm room',
	'College- picked up the wrong book when we bumped into each other',
	'College- hey exchange student why don’t you can come to mine for thanksgiving??',
	'College- walked in on you in the shower',
	'College- drunkenly hooked up but you’re dating my roommate who already hates me',
	'College- the always-partying kid falls for the always-studying kid',
	'College- heard a scream and thought you were getting killed but it was just a spider',
	'College- i really hate you but you have the highest grades in class and i need help',
	'College- waiting in line at registration because for some reason, the computer system wouldn’t just let us sign up for classes there',
	'College- I don’t mind that my roommate’s boyfriend stays over constantly; I mind that he walks around our apartment-style housing naked',
	'College- excuse me, I know we don’t have assigned seats in college, but I’ve been sitting in this one for eight weeks and it seems you’re in my spot',
	'College- I’m exhausted, feverish, and hacking up a lung, and the student health center’s first suggestion was pregnancy, can you help me get to the ER in town',
	'College- hey, I left my student ID in my room and you’re the first person who’s walked by my building for hours now, I hate to be such a bother but can you pretty please swipe me in, it’s freezing',
	'College- bless the spring semester stage combat class for practicing on the North Lawn, because watching my crush get sweaty and worked up while pretending to fight people really Does Things to me, okay',
	'College- oh, jesus, that annoying group of LARPers is playing D&D on the lawn underneath my window again and I’m trying to fucking sleep, I have a fucking midterm tomorrow',
	'College- there’s a cute punk who I keep chatting up at the bike racks outside the library and one of the lecture halls, and I kinda have a crush, but there’s no way they’d ever think of me like that, right?',
	'College- I know that this probably isn’t a good idea but it’s included in the meal plan and I’m stressed out, so I keep hitting the ice cream sundae bar in the buffet style dining hall at least a couple times a week',
	'College- fuck shit fuck please help me, I’m supposed to be in chemistry for non-science majors but somehow, my little humanities major ass got registered into the really hardcore chem class',
	'College- if I pretend to be interested in your student social activism oriented club and help you hand out flyers and run your bake sale and shit, is there a chance that you’ll go with me to the spring Sleaze Ball dance',
	'College- somehow, we always end up sitting next to each other during the weekly gatherings to watch a TV show in our dorm’s really good TV room',
	'College- I was abroad last semester and forgot to fill out the housing form, but your old roommate dropped out so hi, hey, how’s it going, I guess we live together now',
	'College- i thought you were my new roommate’s boyfriend so i casually invited you in but you’re actually the RA of the dorm and now you think i want to have sex with you',
	'College- i accidentally flooded the laundry room and you really needed to do laundry',
	'College- i took a bunch of free condoms from health services just because i could and they all fell out of my bag at once and now you’re staring at me weirdly',
	'College- we have to go camping together and share a sleeping bag even though we’re complete strangers',
	'College- the cereal dispenser in the dining hall broke while i was getting froot loops and now they’re all over the floor and you blame me ',
	'College- we argued so much during a class discussion that we both got kicked out and we’re still arguing outside of class',
	'Autumn- met at a pumpkin patch fighting over the same perfectly round and picturesque pumpkin',
	'Autumn- me and my roommate decided to decorate our house for halloween but got really into it, and ended up re-enacting several scenes from nightmare on elm street so loud the neighbours called the police to investigate screams',
	'Autumn- i ordered a pumpkin spice latte at starbucks and you made a heart with the foam and i decided to drink it here so i can smile at you some more',
	'Autumn- this stranger on the street corner looks like they’re severely unprepared for this cold weather, here, take my scarf, i was planning on donating it to goodwill anyways',
	'Autumn- i was unaware that there was an organized zombie crawl going on and i didn’t realize you were in a costume and i screamed in your face because i truly thought i was facing a zombie invasion',
	'Autumn- i got caught staring at my adult neighbour raking up a bunch of leaves in their backyard and jumping into them and now have to awkwardly pretend i saw nothing',
	'Cold Outside- you walked here in a blizzard to get your hot chocolate but you forgot your wallet at home, here, let me buy your drink for you',
	'Cold Outside- my friends want to skate / ski / snowboard but i don’t know how, can you help me?',
	'Cold Outside- i always thought you were weird for carrying an umbrella in the snow, but now it’s snowing REALLY hard and we’re going the same way',
	'Cold Outside- it’s so cold my mouth is numb, you should kiss me before we get frostbite',
	'Cold Outside- it’s so cold and the only reason we’re outside at all is because we need to walk our dogs',
	'Cold Outside- so you’re the kindly neighbour that shovelled my front walk this morning? you should come round for dinner, i owe you one',
	'Cold Outside- so we’re stuck on a ski lift together',
	'Cold Outside- i forgot my toboggan in the park only to come back and find you using it',
	'Cold Outside- when i wake up and look out the window, there’s a message for me in the snow in my front yard',
	'Cold Outside- we’re playing truth or dare in our friend’s hot tub and you make me get out and stand in the snow in my bare feet, i’m gonna get you back',
	'Cold Outside- the classic huddling together for warmth trope',
	'Cold Outside- you’re an ice dancer and i’m your coach and when you twirl your partner around i wish i was them instead',
	'Cold Outside- we’re both out snowmobiling but yours breaks down, i can give you a lift',
	'Cold Outside- we’re at the mall when there’s a severe weather warning over the loudspeakers, guess we’re spending the night here',
	'Cold Outside- i meant for that snowball to hit my friend but you came around the corner at the last second and now we’re having a snowball fight',
	'Meet Ugly- I broke your nose at a mosh pit',
	'Meet Ugly- I hit you with my car and was the only one to visit you in the hospital',
	'Meet Ugly- You were chased by the cops, got in my car and just yelled ‘Drive!’',
	'Meet Ugly- You punched me in the face while gesticulating wildly to a friend',
	'Meet Ugly- You laughed in a restaurant but you have an ugly laugh and I thought you were choking, so I spent the last three minutes awkwardly humping you while performing the Heimlich maneuver',
	'Meet Ugly- We met each other on a Sunday morning, both doing our walk of shame',
	'Meet Ugly- I get really sick on roller-coasters and you had the misfortune of sitting in front of me so, uh… sorry…',
	'Meet Ugly- You’re the bastard who keeps parking right in front of my house so I retaliated by keying your car and you caught me',
	'Meet Ugly- I work at a department store and if you take out and unfold a shirt and then leave it one more time I’m going to stuff it down your throat',
	'Meet Ugly- You broke into my apartment drunk thinking it was your friend’s house and I should call the cops but my cat kinda likes you so we’re good',
	'Meet Ugly- My new dealer has friended me on Facebook and I’m unsure of how to react to that',
	'Meet Ugly- You saw me reading the same book you did and we got into a heated discussion on how much it sucks',
	'Meet Ugly- This is a five-hour-long plane ride, we’re sitting together and you’re deathly afraid of flying',
	'Art School- you’re a life model and i’m an artist',
	'Art School- hi i need to draw someone for an assignment',
	'Art School- i keep coming back to the print shop because my colours aren’t coming out right but also you’re really cute',
	'Art School- you’re the opinionated one who always has a lot to say during critique but when i ask you out on a date you just blush and say yes',
	'Art School- you’re trying to get your giant canvas into the elevator and you better watch out before you knock someone down, here, let me help you',
	'Art School- in any public place: i could swear you keep looking at me, hang on are you drawing me',
	'Art School- i borrowed some of your paintbrushes in class bc i forgot mine but i accidentally left with them',
	'Art School- as part of an installation you’re doing you stand in the main hall dressed in white from head to toe with a sign inviting people to draw on you, so i leave my number on your back and you actually call',
	'Art School- i’m new here can you help me find the printmaking studios? what do you mean you’re lost too',
	'Art School- help me out while i paint this mural? someone’s got to hold the ladder',
	'Art School- so we’re the only ones in the kiln room, huh',
	'Art School- so we’re the only ones in the darkroom, huh',
	'Art School- i bumped into you and your paint box fell and your stuff spilled out everywhere, oh god i’m so sorry',
	'Art School- i need to make a plaster cast of someone’s face/body part, any volunteers',
	'Art School- they painted over that one wall in the main staircase again so i was going to paint some cool graffiti on it but you got there first',
	'Femslash- fake dating my best friend to have someone to vent to on family gatherings. meanwhile pissing off my conservative uncle i never liked anyway and then pretending to date even though noone is around',
	'Femslash- my new neighbor is smoking hot and i didn’t even like women until now and she has a garden and plants flowers in her bikini and i am dying inside',
	'Femslash- the obligatory coffee shop story in which i buy my hot chocolate with cinnamon whenever i feel bad and the cute barista starts drawing little pictures on my cup to make me smile and it always works so i come on days when i don’t actually feel sad',
	'Femslash- excuse you you are sitting on my seat in this lecture and who are you anyway i never saw you before hey wtf are you checking me out?',
	'Femslash- body swap with height difference and lots of awkward ensuing clumsyness',
	'Femslash- we are the only two girls left after all the partnering-up stuff in this heteronormative dancing lesson so let’s dance together i didn’t like any of the guys anyway',
	'Femslash- can i sit with you during this trainride bc the guy over there is giving me the creeps and oh my god are you reading a song of ice and fire?',
	'Femslash- you found me drunk and crying in a bathroom bc my ex dumped me and then you brought me to a taxi and insisted to give me your number so you’d know that i got home safe and then we start texting a lot',
	'Femslash- we bump into each other in the supermarket every friday and we always buy the same ice cream maybe we should eat some ice cream together',
	'Femslash- my mother brought her new partner home and i am slightly pissed off for no reason and then it turns out her partner has a daughter my age and i’ll probably hate her but then we team up to rant about our horribly lovey-dovey parents and it’s delightful bc you are so full of rage',
	'Femslash- i went to a museum to get some inspiration to draw and then i saw you staring at one of the paintings in awe so i drew you and then you saw my picture and i am dying of embarassment',
	'Known But Not Known- my friend can’t stop talking about how they want to set me up with their other friend so we start texting each other and they’re hilarious but shy about meeting and ALSO there’s a cute bike delivery guy who brings my mail at work and winks at me whenever i sign for a package',
	'Known But Not Known- i’m obsessed with a food blogger who writes about cheap ways to be gourmet in your 20s and i flirt with them over comments but they never post pictures of their face and ALSO there’s a really cute grocery bagger at the store down the street who teases me and always asks to join me for dinner and i definitely want to say yes',
	'Known But Not Known- there’s an overnight IT person at school who always answers the phone when i call about a problem with my computer and i totally have a crush on their voice and their exasperation and ALSO the bakery down the street is always running out of my fave scones and the adorable person behind the counter can’t hide their amusement and i think it’s super rude but also super cute',
	'Known But Not Known- my boss is always telling me how perfect her son would be for me and she promises he’s coming to the next holiday party and don’t worry he’s heard all about me too and ALSO there’s this dude i slept with once a couple of months ago and sometimes he still sends me dick pics when i ask him to at 3 in the morning cause seriously dude’s got a good dick',
	'Known But Not Known- our kids are bitter rivals and the only time we ever meet is when we’re both called to the principal’s office and whatever maybe i think you’re kind of cute but your kid’s a monster and ALSO someone keeps buying the last everything bagel at my favorite coffee shop 2 minutes before i get there in the morning and has heard about my plight and has started leaving me bragging notes about it',
	'Known But Not Known- i hired a dog walking company and i’ve never met the person who comes to my apartment but they leave me really cute notes and they give my dog presents and i kind of love them because my dog does and ALSO one of the artists at this gallery opening is hella cute and i want them to paint me like one of their french girls',
	'Awkward Meet- My cat steals underwear and I come home to find you chasing my cat to get your underwear back.',
	'Awkward Meet- I was imitating a fight scene off this anime I watched and accidentally hit you in the face.',
	'Awkward Meet- This horrible umbrella won’t extend! Oh shit I just hit you in the stomach/crotch! I’m so sorry.',
	'Awkward Meet- I needed a drink of water after my shower but I forgot that I opened the blinds to my balcony and you just saw me walk into my kitchen naked.',
	'Awkward Meet- I just tripped and fell face first into your crotch, god end my life now please.',
	'Awkward Meet- I drunkenly tried to fight you and knocked myself out but you were kind enough to take care of me till I woke up.',
	'Awkward Meet- You have just witnessed me cry over the ending to my favorite game before class began please don’t ever tell anyone about this.',
	'Awkward Meet- I thought you were my friend so I slapped your ass in greeting.',
	'Awkward Meet- I sent a selfie of myself in the tub to the wrong number and you responded back with another selfie. Holy shit you’re really attractive.',
	'Awkward Meet- You’re headphones aren’t plugged in all the way so I know you’re listening to educational children’s cartoon theme songs.',
	'Awkward Meet- You just caught me reading hardcore smut fan fiction during class and you’re wondering how I can read this with a blank face.',
	'Awkward Meet- You accidently broke my arm when you fell from a tree and landed on top of me.',
	'Awkward Meet- I got my ass handed to me in SSB4 by this little kid and you were there to witness it.',
	'Awkward Meet- I’ve never talked to you before but the teacher just used us as an example for a scenario where we are married.',
	'Awkward Meet- Hello we are full grown adults fighting over this last balloon that’s shaped like a cats head.',
	'Awkward Meet- I’m running late to school and you just hit me with your motorcycle cause you’re also late and no I don’t want to go to the hospital instead because I cannot miss this test just please give me a ride instead?',
	'Awkward Meet- Please don’t tell anyone that I carry a stuffed animal around with me and even talk to it.',
	'Awkward Meet- Hello I’m your boss and you’re the new employee who just saw me shove an entire cupcake into my mouth.',
	'Awkward Meet- I’m watching The Lion King on my phone and I’m trying to hide the fact I’m sobbing uncontrollably but you notice anyway.',
	'Awkward Meet- I was trying to ask for directions and you accidentally pepper sprayed me cause you thought I was your stalker.',
	'Awkward Meet- Hey you called this number at like 3AM and we talked about some pretty heavy shit do you remember any of that?',
	'Airport- i fell asleep on your shoulder and you were too polite to move or wake me up',
	'Airport- we have the same luggage and didn’t check the tags before we left so i’m calling you to exchange suitcases (and you also had some interesting things in your bag so i’m excited to meet you)',
	'Airport- author of book gets seated next to someone reading their book and making entertaining faces at each scene', 
	'Airport- bonding solely via eye contact over that annoying person on our plane that we’re both slowly becoming more and more exasperated about',
	'Airport- you fell asleep and i started making funny faces at your kid to keep them amused and the steward mistook us for a couple',
	'Airport- i’m afraid of flying and you were incredibly helpful and tolerant and sweet about it',
	'Airport- i made a horrible first impression at the gate or in line for airport food but now we’re sitting next to each other',
	'Drunk pub karaoke night- Person A is really good and Person B sounds like a strangled cat',
	'Bartender/Landlord- Person A comes in regularly at the same time every week and has a friendly relationship with the bartender (Person B) but then they don’t turn up and Person B gets worried',
	'Pub busker- Person A makes most of their money performing in pubs and Person B sees them one night (Bonus- Person B gets Person A signed)',
	'Pub Quiz- A and B are put on the same team',
	'Pub Quiz- A and B are put on opposite teams and get really competitive',
	'Pub- A and B end up getting thrown out over loudness and nearly starting a fight and have to awkwardly apologise to each other outside',
	'Royal- your country’s trying to take over/annex my country and you’re making it difficult to hate you because you’re so nice and attractive stop it',
	'Royal- we’ve been engaged to be married since we were three but this is the first time we’ve met and your portraits really don’t do you justice',
	'Royal- i’m a prince/ss and you’re a servant and we’re not supposed to hang out but we’re gonna fall in love anyways',
	'Royal- i’m a prince/ss and you’re my bodyguard and we’re so not supposed to bang but we kind of did anyways',
	'Royal- i grew up not knowing i was royal and suddenly my royal grandparent showed up out of nowhere and told me i was so now i guess i’m the heir to the throne and you’re my crush from my pre-royal days but i still have a crush on you',
	'Royal- i grew up not knowing i was royal and now i guess i’m heir to a throne and you’re the guy who’s supposed to be teaching me how to be royal bc i suck at it and oops we made out',
	'Royal- i’m a prince/ss from a small country nobody’s heard of and i’m in college pretending not to be royal and you’re another student who’s always calling me out on my bs',
	'Royal- my country’s going through some issues so i’m here in hiding and you’re a civilian who lives in the same apartment complex as me',
	'Assassin- Wait, you’ve been hired to killthis guy too?!',
	'Assassin- My apologies, upon closer inspection it turns out that you are not the person I was hired to kill.',
	'Assassin- I haven’t decided if I’m actually going to kill you yet but first, either way, what did you DO to piss off the Canadians so badly.',
	'Assassin- They never told me the target was also a trained killer. Did they tell you?',
	'Assassin- I’m meant to kill you but I’ve been watching you for a week to work out how and you’re just too nice.',
	'Assassin- I’m intrigued; the last three attempts on my life were much better funded and prepared.',
	'Assassin- All my intel said you’re not meant to be back until next week and I’m sitting here using your flat as a sniper nest to kill a bad guy. This is awkward.',
	'Assassin- I can only assume we’re both missing part of the story here because that was supposed to kill you.',
	'Assassin- Dude, you just shot my arm off. Do they not hire assassins with an aim anymore?',
	'Assassin- Explain to me one more time, why exactly are you so desperate to buy this much Ricin?',
	'Assassin- So let me get this straight. You nuked my entire home city and you still didn’t manage to kill me?',
	'Assassin- Dude, no. If you kill me that just leaves you, the crazy guy and the CAT!',
	'Assassin- I don’t know who you are or how you got in here but I need you to give back at least some of the armoury.',
	'Assassin- Having drawn the short straw I’m the guy who has to explain to you why we can’t take out a hit on an entire landmass.',
	'Assassin- Look, I know we got off on the wrong foot back there but we are literally the only two people on this boat who are not assassins, so…'
	'Opposites Attract- cat person and dog person meet at petco and their pets won’t stop hissing and growling at each other',
	'Opposites Attract- a violinist who only plays classical music and a metal guitarist dislike each other’s preferred genre but have to perform a duet',
	'Opposites Attract- rebellious teenager who’s failing all their classes is assigned a studious tutor',
	'Opposites Attract- really distinguished food critic and fast food chef',
	'Opposites Attract- a hopeless romantic and a horny beast are set up on a blind date',
	'Opposites Attract- the class clown tries to get the pretentious, stoic know-it-all to laugh',
	'Opposites Attract- a morning person and a night person are assigned as roommates',
	'Opposites Attract- a film junkie who hates reading and a bookworm who never watches any movies run into each other between the movie and literature section of a library',
	'Opposites Attract- painter/writer'
	'Opposites Attract- a scary-looking person who unintentionally makes kids cry and a daycare volunteer meet at a children-filled park au',
	'Opposites Attract- a pro swimmer/part time lifeguard and a sunbather who hates water, can’t swim, and only goes to the beach to tan au',
	'Opposites Attract- a hopeless romantic and a single-but-proud meet at a store on valentine’s day. the latter is buying valentine cards ironically, the former buying them sincerely in hopes of getting a date',
	'Roommate- friend of a friend needs a place to stay before they get evicted',
	'Roommate- room mate falls in the shower and breaks an arm',
	'Roommate- room mate has a nightmare and doesn’t want to sit alone at night',
	'Roommate- new room mate cooks alone for the first time and almost burns down the house',
	'Roommate- room mate gets sick and needs tissues and cough sweets and soup',
	'Roommate- overhearing room mate singing in the shower to find out they sound angelic',
	'Party Meet-Funny- i was on my balcony and you started loudly quoting romeo and juliet at me',
	'Party Meet-Funny- spilled my drink down your shirt and then tried to drink it off you',
	'Party Meet-Funny- we had an impromptu rap duet in the middle of the party',
	'Party Meet-Funny- you kept asking everyone to play the cha cha slide then proceeded to pass out when the song started',
	'Party Meet-Funny- you keep shouting "THIS IS MY JAM" at every song that comes on i have a headache the size of nebraska you’re lucky you’re cute',
	'Party Meet-Funny- whenever you saw me you’d shout ‘WHOOOOOOOOO’ really loudly and then do finger guns at me before walking off to god knows where',
	'Party Meet-Funny- you thought I was your friend and pulled me up on the table to dance with you now you’re shirtless and grinding on me',
	'Party Meet-Funny- you got up to the mic and started singing and holy shit you’re really good???',
	'Party Meet-Funny- you started singing the national anthem when it got really quiet',
	'Party Meet-Funny- you’re really bad at beer pong but you do this really cute dance before you throw the ball so I’m letting you stay on my team',
	'Party Meet-Funny- our mutual friend dared the two of us to chug a whole pint of beer and I’m not going to let you beat me',
	'Party Meet-Funny- we both grabbed for the last bottle of the good beer and i’m not saying we’re going to fight for it but we are',
	'Party Meet-Funny- you threw up on my shoes… twice',
	'Rivals to Lovers- We hate each other but we both have a mutual friend so we have to put up with each other AU',
	'Rivals to Lovers- This is a mandatory partner project and since everybody else is taken I have to have you as my partner',
	'Rivals to Lovers- You’re my jerk barista who purposely screws up my name when I order my caffeine fix',
	'Rivals to Lovers- You used to bully/mess with me in elementary school and it turned out it was because you had a major crush on me',
	'Rivals to Lovers- I’m trying to recruit members for my club but you keep stealing away all my potential recruits',
	'Rivals to Lovers- You spoil all the things I’m into and it’s really pissing me off',
	'Rivals to Lovers- So I have to spend the night at my longtime rival’s house, everything will totally be fine because their parents are there (or not)',
	'Rivals to Lovers- If you aren’t serious about this play then leave',
	'Rivals to Lovers- I know you don’t like me but I really need help passing this class',
	'Rivals to Lovers- Don’t tell anyone you saw me crying',
	'Rivals to Lovers- I don’t want to go to this party/dance alone so please be my date',
	'Rivals to Lovers- Just got caught under the mistletoe with my arch-nemesis and now everything is slow changing between us',
	'Rivals to Lovers- You come to the restaurant I work at and choose me as your waiter(ess) every time just to annoy me and I can’t do anything in retribution or I’ll get fired',
	'Rivals to Lovers- I spilled my lunch on this person one time and now they hate me',
	'Competitive- we’re both ‘team leaders’ at a summer camp for children and you may be hot but goddammit my collection of twelve-year-olds are going to beat yours into the dust',
	'Competitive- we kind of got past the point of ‘taking this game of gay chicken too seriously’ when you took your pants off but I really do not mind at all.',
	'Competitive- I used to be the best baker in the neighbourhood but then you showed up at Mrs. Appleby’s 80th birthday with a stack of brownies which almost gave me an orgasm my honour is at stake and I’m going all out for the next event',
	'Competitive- a mutual friend invited us to their laser tag party and we’re the last two alive on opposite teams and goddammit if I’m going down you’re going down with me',
	'Competitive- you’re going to be at the halloween party and you’ve won best costume for the past three years but this year I am wearing the best costume ever if you defeat me I will eat my - wait you actually look really cute when did you turn hot what the fuck',
	'Competitive- we’re always making stupid bets like ‘bet you can’t drink this whole bottle of BBQ sauce’ but then you did and now you’re sick and I feel really bad here let me look after you',
	'Competitive- did you actually just blue shell me on our date you fucker',
	'Bad at Dating- I can’t tell whether this is a date because you asked to see a movie but I’m still not sure you’re queer, and I’m toeing the line because maybe you’re just trying to make friends',
	'Bad at Dating- One of us thinks this is a date but the other thinks it’s an informal job interview',
	'Bad at Dating- I decided to flip a coin about every decision in my life for a week and that’s how we ended up on a date',
	'Bad at Dating- We’re both meant to be going on blind dates with other people but we sat down at the wrong table and got our hopes up',
	'Bad at Dating- We took each other’s underwear from the laundromat by mistake',
	'Bad at Dating- I got drunk and sent a sexy naked pic to my ex but I sent it to you instead by mistake',
	'Bad at Dating- We had one really bad date and never spoke again and now our friends have set us up on a blind date',
	'Bad at Dating- I’m calling to cancel our date because I’m actually in the ER right now, sorry. …I mean, sure, I guess you can come down here, but… okay…',
	'Bad at Dating- We had sex at the office party but we’re both workaholics so we don’t normally date',
	'Bad at Dating- We’re going on a blind date - but wait a moment, aren’t you that went down on me in a back alley behind a club year ago? … what do you mean “which one”?',
	'Bad at Dating- You bought me at a charity auction and you’re probably a serial killer',
	'Bad at Dating- You’re my waiter and I’m on a really crappy date with an asshole',
	'Bad at Dating- Your appointment with a sexual therapist was right after mine and we got talking in the waiting room',
	'Bad at Dating- We’re on a blind date, but wait a moment… aren’t you that guy who gave me a hand job at a Renaissance Faire a year ago?… what do you MEAN “WHICH ONE”?',
	'Bad at Dating- We both picked the same power ballad at karaoke so we sang a duet',
	'Bad at Dating- We’re both trying to take advantage of the unlimited appetizers deal on separate dates at TGI Fridays and I got the mozzarella sticks and I’m on my sixth plate and I want to die, can I PLEASE swap you for some of your wings?',
	'Hot Mess- i met you last night when you were drunkenly patting my dog in my backyard at 3 in the morning and when i asked you what the hell you were doing you slurred something about dogs being great and then you threw up on my feet and then fifteen minutes later you were passed out on my couch so that’s why you’re here right now also what the fuck is your name and why were you patting a dog in a stranger’s backyard in the middle of the night',
	'Hot Mess- i’m an ikea employee and every day for the last week i’ve had to ask you to leave the store bc you keep coming in and sleeping in the beds seriously are you homeless or something i can call a shelter',
	'Hot Mess- i don’t know who you are but we keep running into each other on the street and getting into screaming arguments over the stupidest things and i’m actually looking forward to our next meeting bc you’re annoying as hell but gdi you’re hot as fuck and its kind of fun to argue with you',
	'Hot Mess- i’m in my underpants in a laundromat waiting for my clothes to get washed and your clothes are in the machine next to mine and i noticed that when you put your clothes in they were all covered in blood what the fuck',
	'Hot Mess- last night was a haze for both of us and somehow we woke up hungover in a bed that isn’t either of ours and also neither of us recognize this apartment we should probably get out of here before someone calls the cops on us',
	'Hot Mess- last night was supposed to be a one night stand but we drunkenly got each other’s names tattooed on each other’s ass cheeks so now its kind of hard to forget you',
	'Hot Mess- you found me hanging by my fingertips from your window and i don’t want to tell you i was trying to rob you but idk how else to explain this and i don’t want to go to jail and also you’re kind of cute we should make out when i’m not clinging onto your window ledge for my life',
	'Hot Mess- you’re lying on the floor of the movie theater crying and i’m the employee who has to tell you another movie starts in five minutes so you have to leave and i’m really sorry but im also confused as to why a documentary on lightbugs affected you so much',
	'Hot Mess- i found you sleeping on my balcony when i went out to water my plants why are you here and more importantly how did you get here we’re eighteen floors up’',
	'Hot Mess- i’m having a minor breakdown in the middle of bed bath and beyond and you’re a bewildered shopper who wants to buy plates but also to make sure i’m okay bc im wailing a little bit in the kitchenware section’',
	'Hot Mess- i asked a staff member and they said you’ve been coming to the pound every day to play with the dog i’m taking home today and that’s why you’re getting weirdly emotional',
	'Hot Mess- why are you dancing in your underwear to kelly clarkson in a public bathroom while brushing your teeth',
	'Hot Mess- i called the wrong number and started talking about my life and you only interrupted me after a few a few minutes of me revealing some pretty personal stuff and now youre invested in my life troubles',
	'Hot Mess- you’re a vet and i’m pleading with you to save my goldfish and you’re the first vet i’ve visited to not ask me if i’m sure i don’t want to go and buy another goldfish for three dollars',
	'Hot Mess- it’s my turn to open up the cafe today and you were sleeping under one of the tables when i came in and i don’t know what to say so i’m just sweeping awkwardly around you',
	'Hot Mess- i’m drunk on public transport and you’re high and we both keep looking at each other knowingly',
	'Hot Mess- you found me in a mall crying over a bowl of noodles i dropped and i s2g im not usually like this im just having a really weird week',
	'Hot Mess- you thought i was someone else and started making out with me at a club and you’re really hot so i just went with it and now we’re heading back to your place and idk how to break it to you'
	'Hot Mess- we keep getting arrested at the same protests and at this point i think i’m only starting fights with policemen so i can sit next to you in holding',
	'Hot Mess- you’re the on-call doctor on saturday nights and i’m purposely injuring myself so i can attempt to chat you up while you give me stitches but i s2g the first four times were accidents i just got too attached',
	'Hot Mess- you climbed into the taxi next to me and passed out and the taxi driver made me haul you out of his taxi so he can get more customers and now i’m on the side of the road holding you up by your armpits and hoping you don’t vomit on me',
	'Hot Mess- we started going home together but i was convinced i knew a faster way to your apartment so we took a wrong turn and now we’re lost and drunk and a little cold',
	'Hot Mess- we’re two thirds of the threesome we had last night and we’re walking awkwardly out of the last persons’s apartment together',
	'Hot Mess- i’ve had a really awful day so i started kicking a car out of frustration and it turned out to be your car i’m so sorry',
	'Art School- I cut myself really badly in Printmaking and I’m trying not to bleed everywhere, turns out you carry a bunch of first aid supplies in your bag',
	'Art School- I let you have a few sheets of darkroom photo paper, to pay me back you offered to model privately for my Studio Photography assignment',
	'Art School- I’m a traditional painter who has to take a basic Photoshop class, you’re a graphic design major sitting next to me and getting sucked into helping me out because I’m so terrible at this',
	'Art School- My pottery bowl exploded in the kiln and I feel like a failure, you found me crying about it in the hallway',
	'Art School- Our Figure Drawing teacher is an asshole, you stuck up for me when he started railing on my portraits',
	'Art School- You saw me struggling to carry a giant cardboard sculpture for my installation and helped me get it to class',
	'Art School- I’m zoning out working on this painting and you just stopped me from drinking out of my dirty water cup',
	'Art School- A mutual friend of ours has this whole vision for their Black and White Photography final and we volunteered to be their models without knowing how sexual this shoot would turn out',
	'Business- “banged someone last night and it turns out they’re interviewing me for my new job”',
	'Business- small business next door to each other on the high street w/ similar wares who always fight for customers',
	'Business- rival CEOs who secretly fuck',
	'Business- “oops i accidentally banged my new boss”',
	'Business- “i’m hiring you as a favour to my friend you better be good”',
	'Business- children of parents who are business rivals and they sneak off to make out whenever they’re forced to attend business meetings ',
	'Business- single parent boss who sometimes has to bring the kids into work vs employee who once complained about the boss’ toddler throwing up on their paperwork ',
	'Business- “we’re both competing for the same promotion”',
	'Business- “i’m really really worried you’re gonna fire me can i make up for the massive mistake i made???”',
	'Business- boss/secretary',
	'Business- “uhoh i’m dating my boss’ child and had no idea until i took them as my date to a work function”',
	'Business- office prank war',
	'Business- “i’ve been working for here for about two minutes i have no idea what i’m doing you’ve been here for years please help”',
	'Reincarnation- I fell in love with you three lifetimes ago and I’ve been looking for you ever since but I’ve been starting to give up and my friends’s new crush has your eyes and oh god I’m not going to steal someone’s date just because I’m hoping you’re the person I met in a past life (jk yes I am)',
	'Reincarnation- I’ve met you in every single lifetime and I always hope it will work out but it doesn’t but I’ll still keep finding you again because those few days/months/years together with you are always so worth it',
	'Reincarnation- I meet and fall in love with you in every lifetime at the same age but your age is always different so it never works out and for the first time I’m meeting you when we’re the same age and I’m horrified that I might fuck this up',
	'Reincarnation- I skipped like four cycles of reincarnation and I know you’re pissed at me for leaving you all those lifetimes but it wasn’t my fault please please will you take me back',
	'Reincarnation- We only remember each other in alternating lifetimes so every lifetime we have to find one another and convince each other that we’re soul mates but half the time I won’t believe you and half the time you’re already dating someone else',
	'Reincarnation- I don’t know how to tell you this but the reason you didn’t see me in our last reincarnation cycle is because for some fucked up reason I was reincarnated as your dog',
	'Reincarnation- We keep reincarnating as people who speak different languages and it’s kind of pissing me off because I can never initially confirm if it’s you but at least I keep learning a bunch of cool new languages each lifetime',
	'Neighbor- I just found out that you’re the asshole who has been stealing my coupons from the Sunday newspaper every week and I am going to make. you. PAY!!',
	'Neighbor- You’re mowing your lawn at 5AM and that is completely unacceptable and I’m going over to your house to yell at you about how unacceptable this is',
	'Neighbor- I always see you doing weird shit at ridiculous hours of the night and it makes me feel better because I do weird shit in the middle of the night too',
	'Neighbor- You greeted me in the strangest way this morning when I was getting my mail and we’ve been neighbors for like 3 years and this is the first time you’ve ever spoken to me I have no idea what is going on',
	'Neighbor- It’s like 3AM and my roommate locked me out of the house and I forgot my keys and I’m really drunk pls take pity on me and let me crash at your place for the night o’ neighbor of mine',
	'Neighbor- You’re a famous viner and I constantly witness you doing the weirdest things',
	'Neighbor- You live in the apartment above me and your water pipe burst and is flooding into my apartment and you can hear me yelling so you come down to my apartment to see what’s going on and witness me standing in my kitchen/bathroom/whatever, holding an umbrella, screaming at the water pouring out of my ceiling and crying because I have no idea what to do and we both just kinda stand there in shock as my stuff gets ruined and you let me crash in your apartment until my apartment gets fixed because you feel bad',
	'Neighbor- You keep borrowing shit from my tool shed without even asking',
	'Neighbor- I just moved in next door and I’m like 99% sure you’re insane',
	'Neighbor- Every year we both go all out for holiday decorating and we’ve developed this rivalry so intense that we’re p much famous in our town for it',
	'Neighbor- We’re both single parents and our kids are best friends with each other',
	'Neighbor- In which we live in a relatively rich neighborhood and during summers we obnoxiously sit in loungers, drinking lemonade, and ogle the cute pool boy together',
	'Neighbor- The walls in this apartment building are really thin and I can hear you having mental breakdowns all the time are you okay?',
	'Neighbor- You’re one of those annoying people who tries to make casual conversation all the time and brings people baked goods and stuff and I just want to mind my own business but somehow we end up being friends or something??',
	'Neighbor- This is the first time I’m living on my own and my parents decided to spontaneously drop by in a few hours to see how I’m doing pls let me borrow some cleaning supplies and food so that my parents will believe I’m a functioning, responsible adult who totally cleans and doesn’t just have condiments and eggs in my fridge',
	'Neighbor- We have weekly get-togethers where we gossip about our other neighbors',
	'Neighbor- Your dog keeps pooping on my lawn',
	'Neighbor- You just moved in next door and you’re convinced your house is haunted so you seek refuge at my house when you get freaked out and eventually rope me into investigating for paranormal activity and the only reason I’m doing any of this is because you’re really freaking cute',
	'Neighbor- All of our other neighbors are crazy so we bond over that fact that we’re the only normal people on the whole street',
	
]

function newPrompt() {
	const randomPrompt = Math.floor(Math.random() * (prompts.length));
	document.getElementById('promptDisplay').innerHTML = prompts[randomPrompt];
}